language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "8"
script:
  - npm test
deploy:
  provider: npm
  email: apexearth@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
after_success: npm run coveralls
